const carreersData2 = [
    { id: 1, 
      title: 'CIENTIFICO DE DATOS JR', 
      image: require('../assets/BANORZ.jpg'),
      description: 'MEXICO, Ciudad de México, MX.',
      fulldescription: 'Cuajimalpa, CDMX \n \n'
                        + 'En Banorte buscamos talento único, fuerte y '
                        + 'extraordinario, que impulse la transformación e '
                        + 'innovación del país, convirtiéndonos en un gran '
                        + 'aliado para crecer fuerte con México. ' 
                        + '\n\n'
                        + 'Estamos convencidos que la combinación de '
                        + 'solidaridad, innovación, respeto, lealtad y '
                        + 'responsabilidad es la fórmula perfecta para '
                        + 'ser el mejor equipo del sector financiero.' 
                        + '\n\n'
                        + 'Objetivo del puesto:\n'
                        + 'Nuestro Subdirector de Analítica de Segmentos '
                        + 'deberá liderar el desarrollo, producción y '
                        + 'seguimiento de insights y modelos analíticos '
                        + 'avanzados enfocados en la segmentación de clientes '
                        + 'para una hipersonalización de ofertas y '
                        + 'optimización del valor del cliente.'
                        + '\n\n'
                        + 'Deberá analizar información e incorporar '
                        + 'herramientas estadísticas y de ML para resolver '
                        + 'problemas específicos de las distintas líneas de '
                        + 'negocio del Banco enfocadas al crecimiento del '
                        + 'valor de los clientes. Los proyectos con diversas '
                        + 'temáticas y de corto plazo, desarrollo de ' 
                        + 'iniciativas de punta a punta, la comunicación y '
                        + 'sinergia con distintas áreas del Banco para la '
                        + 'implementación de los análisis serán parte de '
                        + 'su día a día. '
                        + '\n\n'
                        + 'Cada día te encontrarás ante nuevos e interesantes '
                        + 'retos dentro de tu puesto, en los cuales serás '
                        + 'responsable de: \n'
                        + '• Validación de la información para análisis '
                        + 'estadístico. \n'
                        + '• Automatizar procesos/modelos/análisis que se '
                        + 'van generando. \n'
                        + '• Investigar sobre métodos analíticos o '
                        + 'estadísticos para resolver problemas nuevos. \n'
                        + '• Análisis cuantitativo de información y/o modelaje '
                        + 'estadístico/ML (segmentación, análisis descriptivo, '
                        + 'optimización, ML, etc). \n'
                        + '• Identificar oportunidades analíticas para la '
                        + 'toma de decisiones. \n'
                        + '• Generar sinergias entre distintas áreas para la '
                        + 'implementación de oportunidades identificadas. \n'
                        + '• Seguimiento de resultados de las oportunidades '
                        + 'identificadas, mediante la definición y '
                        + 'construcción de métricas enfocadas en el valor '
                        + 'del cliente.'
                        + '\n\n'
                        + 'Requisitos: \n'
                        + '• Licenciatura en Economia aplicada, Matemáticas '
                        + 'aplicadas. \n'
                        + '• Maestría en Estadística, Ciencia de Datos o '
                        + 'áreas afines. \n'
                        + '• 2 años de experiencia laboral.\n'
                        + '• Experiencia en analítica, ciencia de datos '
                        + '(modelaje estadístico/ML) y programación. \n'
                        + '• Experiencia en programación avanzada en Python, '
                        + 'R, SAS, SQL, Spark, Cloud. \n'
                        + '• Idiomas: Español / Inglés. \n'
                        + '• Disponibilidad para cambio de residencia: N/A. \n'
                        + '• Orientado a resultados, cumplimiento de metas y '
                        + 'planeación.'},
    { id: 2, 
      title: 'AUXILIAR ADMINISTRATIVO', 
      image: require('../assets/BANORZ.jpg'),
      description: 'Puebla, MX.',
      fulldescription: 'Puebla, MX. \n \n'
                        + 'En Banorte buscamos talento único, fuerte y '
                        + 'extraordinario, que impulse la transformación e '
                        + 'innovación del país, convirtiéndonos en un gran '
                        + 'aliado para crecer fuerte con México. \n\n'
                        + 'Estamos convencidos que la combinación de '
                        + 'solidaridad, innovación, respeto, lealtad y '
                        + 'responsabilidad es la fórmula perfecta para ser '
                        + 'el mejor equipo del sector financiero. \n\n'
                        + 'Objetivo del puesto: Llevar un control de '
                        + 'información, atención a clientes, dar seguimientos '
                        + 'a procesos y asistencia de oficina. \n\n'
                        + 'Cada día te encontrarás ante nuevos e interesantes '
                        + 'retos dentro de tu puesto, en los cuales serás '
                        + 'responsable de: \n'
                        + '• Desarrollar habilidades en captura de '
                        + 'información, aprender nuevas plataformas de '
                        + 'sistema de información, facturacion, además de '
                        + 'control de información. \n'
                        + '• Aplicar procesos para llevar un control de '
                        + 'trabajo y hacer eficiente la operación. \n'
                        + '• Establecer metas, compromisos para cumplir '
                        + 'con el puesto y trabajar en equipo. \n\n'
                        + 'Requisitos: \n'
                        + '• Formación profesional Administración de empresas '
                        + 'o contabilidad. \n'
                        + '• Años de experiencia: 1 año.\n'
                        + '• Áreas de experiencia: Administración, '
                        + 'facturacion, captura de datos, sacar copia, '
                        + 'escanear, hacer comunicados. \n'
                        + '• Conocimientos requeridos: paquetería. \n'
                        + '• Idiomas: español. \n'
                        + '• Disponibilidad para viajar: no. \n'
                        + '• Disponibilidad para cambio de residencia: no. \n'},
    
    { id: 3, 
      title: 'AUXILIAR OPERACIONES ADQUIRENTE', 
      image: require('../assets/BANORZ.jpg'),
      description: 'MONTERREY, Nuevo León, MX',
      fulldescription: 'MONTERREY, Nuevo León, MX \n \n'
                        + 'En Banorte buscamos talento único, fuerte y '
                        + 'extraordinario, que impulse la transformación e '
                        + 'innovación del país, convirtiéndonos en un gran '
                        + 'aliado para crecer fuerte con México. \n\n'
                        + 'Estamos convencidos que la combinación de '
                        + 'solidaridad, innovación, respeto, lealtad y '
                        + 'responsabilidad es la fórmula perfecta para ser '
                        + 'el mejor equipo del sector financiero. \n\n'
                        + 'Objetivo del puesto: \n\n'
                        + 'Análisis y validación de datos del proceso de '
                        + 'Originación Adquirente Agregadores, Sub Afiliados '
                        + 'y Ligas de Pago en los aplicativos relacionados al '
                        + 'proceso. \n\n'
                        + 'Cada día te encontrarás ante nuevos e interesantes '
                        + 'retos dentro de tu puesto, en los cuales serás '
                        + 'responsable de: \n'
                        + '• Gestionar las urgencias, escalamientos y folios '
                        + 'vencidos y por vencer de Ligas de Pago. \n\n'
                        + '• Actividades relacionadas a la Originacion y '
                        + 'supervisión. \n'
                        + '• Consolidar y validar reportería de Procesos de '
                        + 'Liga de pagos y agregadores. \n\n'
                        + 'Requisitos: \n'
                        + '• Formación profesional: Licenciatura. \n'
                        + '• Años de experiencia: 2 años. \n'
                        + '• Áreas de experiencia: adquirente, servicio al '
                        + 'cliente, etc. \n'
                        + '• Conocimientos requeridos: Altamira. \n'
                        + '• Idiomas: inglés básico. \n'
                        + '• Disponibilidad para viajar: NA. \n'
                        + '• Disponibilidad para cambio de residencia: NA. \n'},
    { id: 4, 
      title: 'ESPECIALISTA JR INNOVACION Y TRANSFORMACION', 
      image: require('../assets/BANORZ.jpg'),
      description: 'MEXICO, Ciudad de México, MX.',
      fulldescription: 'MEXICO, Ciudad de México, MX.\n \n'
                        + 'En Banorte buscamos talento único, fuerte y '
                        + 'extraordinario, que impulse la transformación e '
                        + 'innovación del país, convirtiéndonos en un gran '
                        + 'aliado para crecer fuerte con México. \n'
                        + 'Estamos convencidos que la combinación de '
                        + 'solidaridad, innovación, respeto, lealtad y '
                        + 'responsabilidad es la fórmula perfecta para ser '
                        + 'el mejor equipo del sector financiero. \n\n'
                        + 'Objetivo del puesto: \n'
                        + '• El objetivo del puesto de Especialista Jr '
                        + 'Innovación y Transformación se basa en gestionar '
                        + 'las iniciativas de transformación digital de '
                        + 'procesos en las distintas áreas del Banco, desde '
                        + 'el análisis y entendimiento del proceso en su '
                        + 'situación actual hasta el rediseño y '
                        + 'transformación de este basado la priorización de '
                        + 'las áreas de oportunidad identificadas y '
                        + 'sustentadas en un análisis cualitativo y '
                        + 'cuantitativo de datos. \n'
                        + '• Facilitar y acompañar a los usuarios en la '
                        + 'implementación de las soluciones de '
                        + 'transformación, guiándolo en el aseguramiento '
                        + 'del cumplimiento de objetivos a través del '
                        + 'monitoreo y control de los resultados del '
                        + 'proceso. \n\n'
                        + 'Cada día te encontrarás ante nuevos e '
                        + 'interesantes retos dentro de tu puesto, en los '
                        + 'cuales serás responsable de: \n'
                        + '• Diseñar y transformar procesos a través de la '
                        + 'reingeniería y evolución digital buscando '
                        + 'optimizar, eficientar la operatividad de las '
                        + 'distintas áreas del banco. \n'
                        + '• Gestionar, desde una visión integral, el '
                        + 'proyecto en términos del plan de atención, '
                        + 'recursos, cumplimiento de actividades e '
                        + 'identificación de riesgos. \n\n'
                        + 'Requisitos: \n'
                        + '• Formación profesional: Ingeniera Industrial, '
                        + 'sistemas computacionales o Licenciaturas con '
                        + 'carreras afines.\n'
                        + '• Años de experiencia: Al menos 3 años. '
                        + 'Preferente en sector financiero. \n'
                        + '• Áreas de experiencia: Análisis, Diseño y '
                        + 'transformación de procesos, Transformación digital '
                        + 'administración y gestión de proyectos, '
                        + 'relacionamiento con usuarios , Análisis '
                        + 'cualitativo y cuantitativo de datos de proceso. \n'
                        + '• Conocimientos requeridos: en Scrum, gestión de '
                        + 'requerimientos, design thinking, Six Sigma, Marco '
                        + 'Lean. \n'
                        + '• Idiomas: inglés básico/medio. \n'
                        + '• Disponibilidad para viajar: No. \n'
                        + '• Disponibilidad para cambio de residencia: No, \n'},
    { id: 5, 
      title: 'AUXILIAR CAPTURA TDC',
      image: require('../assets/BANORZ.jpg'),
      description: 'MONTERREY, Nuevo León, MX.',
      fulldescription: 'MONTERREY, Nuevo León, MX. \n \n'
                        + 'En Banorte buscamos talento único, fuerte y '
                        + 'extraordinario, que impulse la transformación e '
                        + 'innovación del país, convirtiéndonos en un gran '
                        + 'aliado para crecer fuerte con México. \n'
                        + 'Estamos convencidos que la combinación de '
                        + 'solidaridad, innovación, respeto, lealtad y '
                        + 'responsabilidad es la fórmula perfecta para ser '
                        + 'el mejor equipo del sector financiero. \n\n'
                        + 'Objetivo del puesto: Captura y administración '
                        + 'de solicitudes de tarjeta de Crédito. \n\n'
                        + 'Cada día te encontrarás ante nuevos e '
                        + 'interesantes retos dentro de tu puesto, '
                        + 'en los cuales serás responsable de: \n'
                        + '• Captura de solicitudes de crédito en '
                        + 'sistemas internos. \n'
                        + '• Recuperación de trámites rechazados. \n'
                        + '• Seguimiento con áreas internas. \n'
                        + '• Revisión y validación de solicitudes y '
                        + 'documentos. \n'
                        + '• Manejo de bases de datos en Excel. \n'
                        + '• Tareas Administrativas: \n'
                        + '• Archivar documentos. \n'
                        + '• Seguimiento de solicitudes. \n\n'
                        + 'Requisitos: \n'
                        + '• Formación profesional: Licenciatura Económico '
                        + 'Administrativo terminada deseable o en curso '
                        + 'demostrable. \n'
                        + '• Años de experiencia:1 año de experiencia en '
                        + 'puestos administrativos. \n'
                        + '• Áreas de experiencia: Administrativas. \n'
                        + '• Conocimientos requeridos: Paquetería Office '
                        + '(Básico). \n'
                        + '• Idiomas: No. \n'
                        + '• Disponibilidad para viajar: No. \n'
                        + '• Disponibilidad para cambio de residencia: No. \n'
                        + '• PRESTACIONES SUPERIORES BANCARIAS*. \n'
                        },
    { id: 6, 
      title: 'ESPECIALISTA DE ESTRATEGIA BPP', 
      image: require('../assets/BANORZ.jpg'),
      description: 'MEXICO, Ciudad de México, MX.' ,
      fulldescription: 'Reforma 115,Ciudad de México) \n \n'
                        + 'En Banorte buscamos talento único, fuerte y '
                        + 'extraordinario, que impulse la transformación e '
                        + 'innovación del país, convirtiéndonos en un gran '
                        + 'aliado para crecer fuerte con México. \n\n'
                        + 'Estamos convencidos que la combinación de '
                        + 'solidaridad, innovación, respeto, lealtad y '
                        + 'responsabilidad es la fórmula perfecta para ser '
                        + 'el mejor equipo del sector financiero. \n\n'
                        + 'Objetivo del puesto: Asesorar a los banqueros en '
                        + 'temas referentes a los mercados financieros, con '
                        + 'enfoque en asset allocation y mercados de '
                        + 'capitales desde una perspectiva fundamental. '
                        + 'Emitir recomendaciones y generar ideas de '
                        + 'inversión para productos estructurados y '
                        + 'portafolios modelo. \n\n'
                        + 'Cada día te encontrarás ante nuevos e '
                        + 'interesantes retos dentro de tu puesto, en los '
                        + 'cuales serás responsable de: \n'
                        + '• Asesoría y atención a los Asesores de la Banca '
                        + 'Patrimonial y Privada (BPP) con respecto a asset '
                        + 'allocation, con enfoque especial en el mercado de '
                        + 'capitales. \n'
                        + '• Generación de ideas de inversión para productos '
                        + 'estructurados con visión bottom-up. Due '
                        + 'diligence de los subyacentes. \n'
                        + '• Generación de ideas de inversión para '
                        + 'portafolios modelo con visión top-down. Due '
                        + 'diligence de los subyacentes. \n'
                        + '• Apoyo en mantenimiento, seguimiento y '
                        + 'estrategia de portafolios modelo. Desarrollo de '
                        + 'estrategia de capitales sectorial y regional. \n'
                        + '• Realizar Webinars para Clientes y Asesores '
                        + 'sobre temas de mercado. \n'
                        + '• Coordinar, informar, difundir y dar seguimiento '
                        + 'a las ofertas públicas de capitales en donde '
                        + 'Banorte sea partícipe. \n\n'
                        + 'Requisitos: \n'
                        + '• Formación profesional: Lic. '
                        + 'Económico-administrativa. \n'
                        + '• Años de experiencia: 6-7 años. \n'
                        + '• Áreas de experiencia: en áreas de research '
                        + '(sell side), estrategia de inversiones y gestión '
                        + 'de activos (buy side), venta de productos '
                        + 'financieros. \n'
                        + '• Conocimientos requeridos: economía, finanzas, '
                        + 'productos bursátiles, inversiones, derivados. \n'
                        + '• Certificación AMIB Figura 3. \n'
                        + '• CFA Charterholder o en proceso. \n'
                        + '• Manejo de Bloomberg, Excel avanzado, VBA. \n'
                        + '• Idiomas: inglés. \n'
                        + '• Disponibilidad para viajar: N/A. \n'
                        + '• Disponibilidad para cambio de residencia: N/A. \n'
                      
    },
    { id: 7, 
      title: 'GERENTE DE RELACION CON NEGOCIO', 
      image: require('../assets/BANORZ.jpg'),
      description: 'MEXICO, Ciudad de México, MX.' ,
      fulldescription: 'Ciudad de México, CDMX \n \n'
                        + 'Objetivo del puesto: \n'
                        + 'Gestionar el portafolio (Riesgo-crédito) '
                        + 'de bancos extranjeros e instituciones financieras '
                        + 'internacionales. Realizar análisis financiero de '
                        + 'contrapartes y análisis macroeconómico, para la '
                        + 'aprobación de líneas ante Comités de Crédito y '
                        + 'para el monitoreo del portafolio. \n\n'
                        + 'Realizar proyectos para la mejora de la '
                        + 'rentabilidad del portafolio. Mantenimiento de '
                        + 'relaciones de negocio con bancos extranjeros. \n\n'
                        + 'Cada día te encontrarás ante nuevos e interesantes '
                        + 'retos dentro de tu puesto, en los cuales serás '
                        + 'responsable de: \n'
                        + '• Llevar a cabo análisis financiero y de crédito; '
                        + 'de contrapartes, sectores, portafolios y países. \n'
                        + '• Preparar presentaciones para Comités de '
                        + 'Crédito. \n'
                        + '• Gestionar líneas existentes y nuevas líneas '
                        + 'de crédito y contraparte. \n'
                        + '• Generar y monitorear reportes de seguimiento '
                        + 'del negocio y la relación. \n'
                        + '• Realizar proyectos de mejora de rentabilidad. \n'
                        + '• Desarrollar relaciones con áreas internas. \n'
                        + '• Diseñar y llevar a cabo proyectos de mejora del '
                        + 'área y de generación de nuevos negocios. \n'
                        + '• Manejar la relación con instituciones '
                        + 'financieras internacionales. \n'
                        + '• Serás responsable de la administración del '
                        + 'portafolio de líneas de contraparte '
                        + 'internacionales para cualquier área de negocio '
                        + 'del Banco (realizar análisis de crédito para '
                        + 'nuevas líneas de negocio y renovaciones de líneas '
                        + 'actuales, análisis de riesgo país, evaluar '
                        + 'oportunidades de negocio con IFIs). \n\n'
                        + 'Requisitos: \n'
                        + '• Formación profesional : licenciatura en áreas '
                        + 'Económico Administrativas, Finanzas, Economía, '
                        + 'Ingenierías (Titulados). \n'
                        + '• Años de experiencia : experiencia laboral en '
                        + 'sector financiero deseable. \n'
                        + '• Experiencia y conocimientos : deseable en '
                        + 'análisis financiero y en crédito, manejo de excel, '
                        + 'análisis de información financiera y estados '
                        + 'financieros, procesos de crédito y gestión de '
                        + 'portafolio de riesgo. \n'
                        + '• Idioma inglés avanzado indispensable. \n'
                        + '• Tercer idioma es un plus. \n'
                        + '• Alta capacidad de análisis. \n'
                        + '• Competencias : análisis, organización, trabajo '
                        + 'en equipo, proactividad y comunicación. \n'
                        + '• Conocimientos requeridos : Microsoft Office, '
                        + 'Excel, Powerpoint, Outlook. \n'
                        + '• Disponibilidad para viajar: Sí. \n'
                        + '• Disponibilidad para cambio de residencia: No. \n'

    },
    { id: 8, 
      title: 'ANALISTA PROMOCION AYF', 
      image: require('../assets/BANORZ.jpg'),
      description: 'CHIHUAHUA, Chihuahua, MX.' ,
      fulldescription: 'CHIHUAHUA, Chihuahua, MX.\n \n'
                        + 'En Banorte buscamos talento único, fuerte y '
                        + 'extraordinario, que impulse la transformación e '
                        + 'innovación del país, convirtiéndonos en un gran '
                        + 'aliado para crecer fuerte con México. \n\n'
                        + 'Estamos convencidos que la combinación de '
                        + 'solidaridad, innovación, respeto, lealtad y '
                        + 'responsabilidad es la fórmula perfecta para ser '
                        + 'el mejor equipo del sector financiero. \n\n'
                        + 'Objetivo del puesto: \n'
                        + 'Asegurar la operación de los productos de '
                        + 'arrendamiento y factoraje con las áreas internas '
                        + 'involucradas en el proceso, considerando el '
                        + 'cumplimiento a las condiciones establecidas por '
                        + 'los comités de crédito, y por la normatividad '
                        + 'interna de GFNorte. \n\n'
                        + 'Establecer una relación integral con el cliente, '
                        + 'de la mano con el Ejecutivo de Cuenta que permita '
                        + 'brindar una correcta atención. Mantener los '
                        + 'expedientes de créditos actualizados, y completos '
                        + 'con apego a la normatividad institucional. \n\n'
                        + 'Cada día te encontrarás ante nuevos e interesantes '
                        + 'retos dentro de tu puesto, en los cuales serás '
                        + 'responsable de: \n'
                        + '1.- Operar la contratación de las líneas de '
                        + 'factoraje. \n'
                        + '2.- Ejecutar la operación de los contratos de '
                        + 'arrendamiento y sus anexos. \n'
                        + '3.- Obtener el cobro de comisiones y vencimientos '
                        + 'de las operaciones de Factoraje, así como el '
                        + 'cobro de los pagos iniciales de un arrendamiento:'
                        + 'rentas extraordinarias, rentas en depósito, '
                        + 'depósitos en garantía y comisiones. \n'
                        + '4.- Realizar la cobranza de las rentas de un '
                        + 'contrato de arrendamiento, y proporcionar al '
                        + 'cliente atención para: prepagos, terminaciones, '
                        + 'devolución de bienes, emisión de facturas o '
                        + 'recibos, trámites ante autoridades de tránsito o '
                        + 'gubernamentales. \n'
                        + '5.- Asesorar a los proveedores de bienes en '
                        + 'arrendamiento en la correcta emisión de las '
                        + 'facturas, así como en la entrega de documentación '
                        + 'para su adhesión al sistema SAP de pago a '
                        + 'proveedores. \n\n'
                        + 'Requisitos específicos: \n'
                        + '• Indispensable contar con título o cédula '
                        + 'profesional. \n'
                        + '• Licenciatura en contabilidad. \n'
                        + '• Excelente presentación y trato. \n '
    },

    // add more news articles here
  ];

  export default carreersData2;