const learningData = [
    { id: 1, 
      title: 'Habilidades Gerenciales LIVE, ITESM.', 
      image: require('../assets/ITESM.jpeg'),
      description: 'Desarrollar habilidades y competencias básicas de liderazgo mediante herramientas prácticas que permitan impulsar la entrega de resultados. \nDirigido a gerentes.' },
    { id: 2, 
      title: 'Liderazgo Transformacional, Harvard HBP.', 
      image: require('../assets/HBP.jpg'), 
      description: 'Desarrollar las habilidades de los subdirectores para gestionar exitosamente a sus equipos por medio de herramientas que les permitan convertirse en líderes capaces, comprometidos y orientados a resultados. \nDirigido a subdirectores.' },
    { id: 3, 
      title: 'Liderazgo y Empresa OnLine, ICAMI.', 
      image: require('../assets/ICAMI.png'), 
      description: 'Perfeccionar las habilidades de negocio en los subdirectores de la institución, desarrollando la capacidad de análisis para la toma de decisiones eficaces y oportunas. \nDirigido a subdirectores.' },
    { id: 4, 
      title: 'Alta Dirección Banorte, IPADE', 
      image: require('../assets/IPADE.png'), 
      description: 'Desarrollar y perfeccionar las habilidades de los directivos para mejorar la toma de decisiones, perspicacia financiera, orientación al cliente, así como pensamiento innovador y estratégico. \nDirigido a directores.' },
    { id: 5, 
      title: 'Dirección de Personas, IPADE.', 
      image: require('../assets/IPADE.png'), 
      description: 'Desarrollar y perfeccionar las habilidades de los directivos, de manera que les permitan crear diagnósticos y tomar decisiones asertivas relacionadas con las personas con las que interactúa. \nDirigido a directores.' },
    { id: 6, 
      title: 'Continuidad y Actualización, IPADE.', 
      image: require('../assets/IPADE.png'), 
      description: 'Perfeccionar las habilidades directivas mediante su práctica intensiva, motivando a desarrollar sus cualidades para la toma de decisiones, ejercitando la flexibilidad y amplitud de criterio, así como la construcción de firmeza de carácter que debe acompañar a toda acción directiva. \nDirigido a: Directores Ejecutivos con experiencia que hayan participado en el programa de Alta Dirección Banorte.' },
    { id: 7, 
      title: 'Coaching Ejecutivo, SHERPA COACHING', 
      image: require('../assets/SHERPA.png'), 
      description: 'Fortalecer las habilidades requeridas para dirigir personas a través de un proceso de coaching individual. \nDirigido a directores ejecutivos.' },

    // add more news articles here
  ];
export default learningData;