const promoData = [
    { id: 1, 
      title: '¡5% OFF en SAMSUNG STORE!', 
      image: require('../assets/SAMSUNG.png'),
      description: 'Banorte te ofrece 5% de descuento con el código: \nSAMSUNGXBANORTE',
      fulldescription: 'Banorte te ofrece 5% de descuento con el código: \nSAMSUNGXBANORTE\n\n\n\n\n\n\n\n\n\n\n\n\n\n'},
    { id: 2, 
      title: '¡2x1 en Cinépolis!', 
      image: require('../assets/CINEPOLIS.jpg'), 
      description: 'Paga con tu tarjeta Banorte y obten 2x1 en Cinépolis con el código: \nCINEPOLISXBANORTE',
      fulldescription: 'Paga con tu tarjeta Banorte y obten 2x1 en Cinépolis con el código: \nCINEPOLISXBANORTE\n\n\n\n\n\n\n\n\n\n\n\n\n\n' },
    { id: 3, 
      title: '¡Chicken Bites gratis!', 
      image: require('../assets/SHAKESHACK.png'), 
      description: 'Banorte te ofrece Chicken Bites gratis en compra minima de $300 con el código: \nSHAKESHACKXBANORTE',
      fulldescription: 'Banorte te ofrece Chicken Bites gratis en compra minima de $300 con el código: \nSHAKESHACKXBANORTE\n\n\n\n\n\n\n\n\n\n\n\n\n\n' },
    { id: 4, 
      title: "¡5% OFF en P.F. CHANG'S!", 
      image: require('../assets/PFCHANGS.png'), 
      description: 'Banorte te ofrece 5% de descuento con el código: \nPFCXBANORTE',
      fulldescription: 'Banorte te ofrece 5% de descuento con el código: \nPFCXBANORTE\n\n\n\n\n\n\n\n\n\n\n\n\n\n' },
    { id: 5, 
      title: '¡15% OFF en STRARBUCKS!', 
      image: require('../assets/STARBUCKS.png'), 
      description: 'Banorte te ofrece 15% de descuento con el código: \nSTARXBANORTE',
      fulldescription: 'Banorte te ofrece 15% de descuento con el código: \nSTARXBANORTE\n\n\n\n\n\n\n\n\n\n\n\n\n\n' },
    { id: 6, 
      title: '¡15% OFF en BEN & FRANK!', 
      image: require('../assets/BENFRANK.png'), 
      description: 'Banorte te ofrece 15% de descuento en tu primer armazón con el código: \nBFXBANORTE',
      fulldescription: 'Banorte te ofrece 15% de descuento en tu primer armazón con el código: \nBFXBANORTE\n\n\n\n\n\n\n\n\n\n\n\n\n\n' },

    // add more news articles here
  ];

  export default promoData;